FROM node:22-alpine3.22
RUN apk add --no-cache mongodb-tools && corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml .npmrc ./
RUN pnpm install --prod --frozen-lockfile --ignore-scripts
COPY backup-worker ./backup-worker
USER node
ENV NODE_ENV=production NODE_OPTIONS=--max-old-space-size=128
CMD ["node", "backup-worker/index.cjs"]
