export const CREATE_FEED_VIDEO_COMMENT_USE_CASE = Symbol('CREATE_FEED_VIDEO_COMMENT_USE_CASE');
export const GET_FEED_VIDEO_COMMENTS_USE_CASE = Symbol('GET_FEED_VIDEO_COMMENTS_USE_CASE');
export const GET_FEED_VIDEO_REPLIES_USE_CASE = Symbol('GET_FEED_VIDEO_REPLIES_USE_CASE');
export const UPDATE_FEED_VIDEO_COMMENT_USE_CASE = Symbol('UPDATE_FEED_VIDEO_COMMENT_USE_CASE');
export const DELETE_FEED_VIDEO_COMMENT_USE_CASE = Symbol('DELETE_FEED_VIDEO_COMMENT_USE_CASE');
