export const CREATE_NOTIFICATION_DISPATCH_USE_CASE = Symbol('CREATE_NOTIFICATION_DISPATCH_USE_CASE');
export const CREATE_NOTIFICATION_FROM_BUILDER_DISPATCH_USE_CASE = Symbol(
    'CREATE_NOTIFICATION_FROM_BUILDER_DISPATCH_USE_CASE',
);
export const SEND_NOTIFICATION_EMAIL_DISPATCH_USE_CASE = Symbol('SEND_NOTIFICATION_EMAIL_DISPATCH_USE_CASE');
