export const BREEDER_EXPLORE_EXAMPLES = {
    dogSearch: {
        petType: 'dog',
        dogSize: ['small', 'medium'],
        province: ['경기도', '서울특별시'],
        city: ['파주시', '강남구'],
        isAdoptionAvailable: true,
        breederLevel: ['new'],
        sortBy: 'latest',
        page: 1,
        take: 20,
    },
    catSearch: {
        petType: 'cat',
        catFurLength: ['short', 'long'],
        province: ['서울특별시'],
        city: ['강남구', '서초구'],
        breederLevel: ['new', 'elite'],
        sortBy: 'favorite',
        page: 1,
        take: 20,
    },
    multipleFilters: {
        petType: 'dog',
        dogSize: ['small', 'medium', 'large'],
        province: ['경기도', '서울특별시', '인천광역시'],
        city: ['파주시', '강남구', '연수구'],
        isAdoptionAvailable: true,
        breederLevel: ['new', 'elite'],
        sortBy: 'review',
        page: 1,
        take: 20,
    },
} as const;

export const BREEDER_CARD_EXAMPLE = {
    breederId: '507f1f77bcf86cd799439011',
    breederName: '해피독 브리더',
    breederLevel: 'new',
    location: '경기도 파주시',
    mainBreed: '말티즈',
    isAdoptionAvailable: true,
    priceRange: {
        min: 1000000,
        max: 2000000,
        display: 'range',
    },
    favoriteCount: 42,
    isFavorited: false,
    representativePhotos: [
        'https://example.com/photo1.jpg',
        'https://example.com/photo2.jpg',
        'https://example.com/photo3.jpg',
    ],
    profileImage: 'https://example.com/profile.jpg',
    totalReviews: 15,
    averageRating: 4.5,
    createdAt: new Date('2024-01-15T09:00:00.000Z'),
};
