name: Task
description: Jira 하위 작업 생성
title: "작업: "
body:
  - type: input
    id: jira-story-number
    attributes:
      label: Story 번호 (PP- 뒤의 숫자만)
      placeholder: "55"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      placeholder: |
        - 구현할 기능
        - 작업 내용
    validations:
      required: true
