name: 🔧 Task
description: 새로운 작업 생성 (Jira Sub-task로 자동 연결)
title: "[TASK] "
labels: ["task"]
body:
  - type: input
    id: jira-story-number
    attributes:
      label: 연결할 Jira Story 번호
      description: PP- 뒤의 숫자만 입력하세요
      placeholder: "예시: 15"
    validations:
      required: true
  
  - type: textarea
    id: description
    attributes:
      label: 작업 설명
      description: 구체적인 작업 내용을 작성하세요
      placeholder: |
        예시:
        - API 엔드포인트 개발
        - 프론트엔드 컴포넌트 구현
        - 테스트 케이스 작성
    validations:
      required: true
