export const TOGGLE_FEED_VIDEO_LIKE_USE_CASE = Symbol('TOGGLE_FEED_VIDEO_LIKE_USE_CASE');
export const GET_FEED_VIDEO_LIKE_STATUS_USE_CASE = Symbol('GET_FEED_VIDEO_LIKE_STATUS_USE_CASE');
export const GET_MY_LIKED_FEED_VIDEOS_USE_CASE = Symbol('GET_MY_LIKED_FEED_VIDEOS_USE_CASE');
