export const CREATE_OR_GET_ROOM_USE_CASE = Symbol('CREATE_OR_GET_ROOM_USE_CASE');
export const GET_MY_ROOMS_USE_CASE = Symbol('GET_MY_ROOMS_USE_CASE');
export const SEND_MESSAGE_USE_CASE = Symbol('SEND_MESSAGE_USE_CASE');
export const GET_MESSAGES_USE_CASE = Symbol('GET_MESSAGES_USE_CASE');
export const CLOSE_ROOM_USE_CASE = Symbol('CLOSE_ROOM_USE_CASE');
